# motor_interface.pyi

from typing import List, Union

# Enum: comm_type
class CommType:
    uart: int
    can: int
    Uart: int
    Can: int

    def __init__(self) -> None: ...
    @staticmethod
    def __members__() -> dict[str, 'CommType']: ...

# Enum: end_type
class EndType:
    gripper: int
    teach: int
    none: int
    Gripper: int
    Teach: int
    None_: int  
    mix: int
    Mix: int

    def __init__(self) -> None: ...
    @staticmethod
    def __members__() -> dict[str, 'EndType']: ...

# Class: motor_core
class S1ARM:
    def __init__(self, port: str, comm: CommType, end: EndType) -> None: ...

    def close(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...

    def control_pos_vel(self, pos: List[float], vel: List[float]) -> None: ...
    def control_pos(self, pos: List[float],tau: List[float]) -> None: ...
    def control_foc(self, torque: List[float]) -> None: ...

    def get_position(self) -> List[float]: ...
    def get_velocity(self) -> List[float]: ...
    def get_torque(self) -> List[float]: ...
    def get_coil_temperature(self) -> List[float]: ...
    def get_mos_temperature(self) -> List[float]: ...
    def gravity(self, pos: List[float]) -> List[float]: ...
    def control_gripper(self, pos: float,foc: float) -> None: ...
    def control_teach(self, max_foc: float) -> None: ...
    def control_teach_pos(self, pos: float) -> None: ...
    def control_mix_gripper(self, pos: float, spd: float, kp: float, kd: float,tau: float) -> None: ...
    def set_zero_position(self) -> None: ...
    def set_end_zero_position(self) -> None: ...
class S1_Kinematics:
    def __init__(self, end_offset:List[float]) -> None: ...
    def fk_quat(self, pos: List[float]) -> List[float]: ...
    def fk_euler(self, pos: List[float]) -> List[float]: ...
    def ik_quat(self, pos: List[float], joint_positions: List[float]) -> List[float]: ...      
    def ik_euler(self, pos: List[float], joint_positions: List[float]) -> List[float]: ...
    
def search_arm(bus: str, comm: CommType, end_effect: EndType) -> bool: ...
